// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://twrmxjarcpsfdojwpfhn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InR3cm14amFyY3BzZmRvandwZmhuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA2ODY0ODAsImV4cCI6MjA2NjI2MjQ4MH0.jB-PgRvbwxL7ODEeutjBi7-uwQ8Obh4I1cs8HpV7zgI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});